os: osx
osx_image: xcode10.2

language: bash

git:
  depth: false

before_cache:
  - brew cleanup

before_install:
  - whoami
  - echo "Start of pipeline"

install:
  - brew install docker
  - docker ps

before_script:
  - git clone https://git.cs.hioa.no/staiyeba/travis-test

script:
  - ls
  - chmod +x hello.sh
  - ./hello.sh
  - docker pull scratch

after_script:
  - echo "End of pipeline"
